description: Deploy the exported object detection model on the chosen cloud platform,
  and expose a REST API for real-time object detection.
input-class: ModelDeployerInputDict
name: ModelDeployer
output-class: ModelDeployerOutputDict
parameters:
  cloud_platform: AWS
